// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file thermal.proto (package thermal, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, ImageFileResponse, PrintResponse, PrintTextRequest } from "./thermal_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service thermal.ThermalPrinterService
 */
export const ThermalPrinterService = {
  typeName: "thermal.ThermalPrinterService",
  methods: {
    /**
     * @generated from rpc thermal.ThermalPrinterService.PrintText
     */
    printText: {
      name: "PrintText",
      I: PrintTextRequest,
      O: PrintResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc thermal.ThermalPrinterService.TakePicture
     */
    takePicture: {
      name: "TakePicture",
      I: Empty,
      O: ImageFileResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

