name: Build Remix Web-UI

on:
  push:
    branches:
      - main # This triggers on pushes to the main branch, including merges

jobs:
  build-webui:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -f apps/web-ui/Dockerfile -t ghcr.io/${{ github.repository}}/message-me-web-ui:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository}}/message-me-web-ui:latest
