name: Build Go Server

on:
  push:
    branches:
      - main # This triggers on pushes to the main branch, including merges

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Go 1.21.6
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.21.x"

      - name: Install dependencies
        working-directory: apps/go-test
        run: go mod tidy

      - name: Build
        working-directory: apps/go-test
        run: GOOS=linux GOARCH=arm GOARM=5 go build -o release/thermal-printer-server-arm .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: apps/go-test/release/thermal-printer-server-arm
          asset_name: thermal-printer-server-arm
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
